title: VTS - Voice Typing Studio
description: Open-source macOS dictation replacement with AI-powered transcription
baseurl: "/VTS"
url: "https://j05u3.github.io"

# Repository information
repository: j05u3/VTS
github_username: j05u3

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Theme settings
theme: minima

# Collections
collections:
  releases:
    output: false

# Exclude from processing
exclude:
  - .github/
  - .gitignore
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - SETUP-AUTOMATION.md
  - SPARKLE-INTEGRATION.md
  - scripts/
  - VTSApp/
  - build/
  - Package.swift
  - Package.resolved
  - .swiftpm/
  - .build/
  - VTSApp.xcodeproj/
  - "*.dmg"
  - "*.sha256"
  - checksums.txt
  - version.txt
  - release-please-config.json
  - .release-please-manifest.json
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
